# Parameters for ROSflight software-in-the-loop simulation.
# Mass and inertia parameters are defined in multirotor.urdf.xacro.

/multirotor/rosflight_sil:
  ros__parameters:
    # Common Global Physical Parameters
    linear_mu: 0.05
    angular_mu: 0.0005
    ground_effect: [ -55.3516, 181.8265, -203.9874, 85.3735, -7.6619 ]

    # Dynamics
    num_rotors: 4
    rotor_positions: [ 0.1926,  0.230, -0.0762,
                      -0.1907,  0.205, -0.0762,
                      -0.1907, -0.205, -0.0762,
                       0.1926, -0.230, -0.0762 ]

    rotor_vector_normal: [ -0.02674078,  0.0223925,  -0.99939157,
                            0.02553726,  0.02375588, -0.99939157,
                            0.02553726, -0.02375588, -0.99939157,
                           -0.02674078, -0.0223925,  -0.99939157 ]

    rotor_rotation_directions: [ -1, 1, -1, 1 ]
    rotor_max_thrust: 14.961
    rotor_F: [ 1.5e-5, -0.024451, 9.00225 ]
    rotor_T: [ 2.22e-7,-3.51e-4,  0.12531 ]
    rotor_tau_up: 0.2164
    rotor_tau_down: 0.1644
