name: clang-format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.16
        with:
          source: '.'
          extensions: 'hpp,cpp'
          clangFormatVersion: 16
